max_iter_to_alter: 25
refinement_steps: 20
iterative_refinement_steps: [0, 10, 20]
scale_factor: 20
attn_res: [16, 16]
steps_to_save_attention_maps: null
do_smoothing: true
smoothing_kernel_size: 3
smoothing_sigma: 0.5
temperature: 0.5
softmax_normalize: true
softmax_normalize_attention_maps: false
add_previous_attention_maps: true
previous_attention_map_anchor_step: null
loss_fn: "ntxent"
conform: false
